CITY_CHOICES = (
    ('dhaka', 'Dhaka'),
    ('chittagong', 'Chittagong'),
    ('sylhet', 'Sylhet'),
    ('khulna', 'Khulna'),
    ('rajshahi', 'Rajshahi'),
    ('barisal', 'Barisal'),
    ('rangpur', 'Rangpur'),
    ('mymensingh', 'Mymensingh'),
    ('comilla', 'Comilla'),
    ('narsingdi', 'Narsingdi'),
    ('coxsbazar', 'Cox\'s Bazar'),
    ('gazipur', 'Gazipur'),
    ('narayanganj', 'Narayanganj'),
    ('narshingdi', 'Narshingdi'),
    ('jamalpur', 'Jamalpur'),
    ('bogra', 'Bogra'),
    ('feni', 'Feni'),
    ('natore', 'Natore'),
    ('noakhali', 'Noakhali'),
    ('pabna', 'Pabna'),
    ('rajbari', 'Rajbari'),
    ('rangamati', 'Rangamati'),
    ('sirajganj', 'Sirajganj'),
    ('tangail', 'Tangail'),
    ('bandarban', 'Bandarban'),
    ('kurigram', 'Kurigram'),
    ('madaripur', 'Madaripur'),
    ('meherpur', 'Meherpur'),
    ('moulvibazar', 'Moulvibazar'),
    ('gopalganj', 'Gopalganj'),
    ('habiganj', 'Habiganj'),
    ('joypurhat', 'Joypurhat'),
    ('kishoreganj', 'Kishoreganj'),
    ('madaripur', 'Madaripur'),
    ('manikganj', 'Manikganj'),
    ('munshiganj', 'Munshiganj'),
    ('nilphamari', 'Nilphamari'),
    ('paulia', 'Paulia'),
    ('pangsha', 'Pangsha'),
    ('pattya', 'Pattya'),
    ('rangpur', 'Rangpur'),
    ('rupsa', 'Rupsa'),
    ('savar', 'Savar'),
    ('thakurgaon', 'Thakurgaon'),
    ('gaibandha', 'Gaibandha'),
    ('pirojpur', 'Pirojpur'),
    ('sherpur', 'Sherpur'),
    ('bhairab', 'Bhairab'),
    ('bhairabkunda', 'Bhairabkunda'),
    ('bholahat', 'Bholahat'),
    ('bhomra', 'Bhomra'),
    ('ghop', 'Ghop'),
    ('haldibunia', 'Haldibunia'),
    ('hatibandha', 'Hatibandha'),
    ('hatikumrul', 'Hatikumrul'),
    ('hili', 'Hili'),
    ('horinmara', 'Horinmara'),
    ('kaligonj', 'Kaligonj'),
    ('kamalpur', 'Kamalpur'),
    ('kamlapur', 'Kamlapur'),
    ('karimganj', 'Karimganj'),
    ('kholahati', 'Kholahati'),
    ('khopa', 'Khopa'),
    ('komarhat', 'Komarhat'),
    ('kushumba', 'Kushumba'),
    ('lalmonirhat', 'Lalmonirhat'),
    ('meherpur', 'Meherpur'),
    ('mohongonj', 'Mohongonj'),
    ('mokamtala', 'Mokamtala'),
    ('noorpur', 'Noorpur'),
    ('panchagarh', 'Panchagarh'),
    ('rajbari', 'Rajbari'),
    ('ratanganj', 'Ratanganj'),
    ('rohimanpur', 'Rohimanpur'),
    ('sakharia', 'Sakharia'),
    ('sathia', 'Sathia'),
    ('sutrapur', 'Sutrapur'),
    ('sutrapur-harla', 'Sutrapur-Harla'),
    ('tamabil', 'Tamabil'),
    ('taraganj', 'Taraganj'),
    ('tarap', 'Tarap'),
    ('torki', 'Torki'),
    ('traibal', 'Traibal'),
    ('ullokathi', 'Ullokathi'),
    ('bangla hili', 'Bangla Hili'),
    ('badarganj', 'Badarganj'),
    ('baufal', 'Baufal'),
    ('belabo', 'Belabo'),
    ('belkuchi', 'Belkuchi'),
    ('birampur', 'Birampur'),
    ('chak bazar', 'Chak Bazar'),
    ('chakaria', 'Chakaria'),
    ('chaklasi', 'Chaklasi'),
    ('chakulia', 'Chakulia'),
    ('chapai nawabganj', 'Chapai Nawabganj'),
    ('dhanbari', 'Dhanbari'),
    ('duarabazar', 'Duarabazar'),
    ('dumuria', 'Dumuria'),
    ('gaforgaon', 'Gaforgaon'),
    ('gongachara', 'Gongachara'),
    ('gulshan', 'Gulshan'),
    ('haflong', 'Haflong'),
    ('haimchar', 'Haimchar'),
    ('hinguli', 'Hinguli'),
    ('husainpur', 'Husainpur'),
    ('jaintiapur', 'Jaintiapur'),
    ('kalibari', 'Kalibari'),
    ('kalurghat', 'Kalurghat'),
    ('kamalpur', 'Kamalpur'),
    ('kaptai', 'Kaptai'),
    ('kapurthala', 'Kapurthala'),
    ('karamdi', 'Karamdi'),
    ('karihati', 'Karihati'),
    ('karimpur', 'Karimpur'),
    ('kasba', 'Kasba'),
    ('kashinathpur', 'Kashinathpur'),
    ('kendua', 'Kendua'),
    ('khagdohor', 'Khagdohor'),
    ('khagrachhari', 'Khagrachhari'),
    ('khasherhat', 'Khasherhat'),
    ('khilkhet', 'Khilkhet'),
    ('khulshi', 'Khulshi'),
    ('kobirhat', 'Kobirhat'),
    ('kolaroa', 'Kolaroa'),
    ('kolompaton', 'Kolompaton'),
    ('korotia', 'Korotia'),
    ('kulaura', 'Kulaura'),
    ('kurigram sadar', 'Kurigram Sadar'),
    ('lakhai', 'Lakhai'),
    ('laupala', 'Laupala'),
    ('laxmipur', 'Laxmipur'),
    ('laxmipur village', 'Laxmipur Village'),
    ('laxmipur village-1', 'Laxmipur Village-1'),
    ('lakshmichhari', 'Lakshmichhari'),
    ('lalabazar', 'Lalabazar'),
    ('lalmonirhat', 'Lalmonirhat'),
    ('lawachara', 'Lawachara'),
    ('madhupur', 'Madhupur'),
    ('mafiapara', 'Mafiapara'),
    ('maishadi', 'Maishadi'),
    ('malda', 'Malda'),
    ('manpura', 'Manpura'),
    ('mansurnagar', 'Mansurnagar'),
    ('mathbaria', 'Mathbaria'),
    ('mirzapur', 'Mirzapur'),
    ('mohonpur', 'Mohonpur'),
    ('mongla', 'Mongla'),
    ('muktagachha', 'Muktagachha'),
    ('mukundapur', 'Mukundapur'),
    ('muladi', 'Muladi'),
    ('muladi p.s', 'Muladi P.S'),
    ('munshiganj', 'Munshiganj'),
    ('nabinagar', 'Nabinagar'),
    ('nabinagar sadar', 'Nabinagar Sadar'),
    ('nakugaon', 'Nakugaon'),
    ('nakuagaon', 'Nakuagaon'),
    ('naktala', 'Naktala'),
    ('narinda', 'Narinda'),
    ('narshingdi', 'Narshingdi'),
    ('nayapara', 'Nayapara'),
    ('nayapara-baishari', 'Nayapara-Baishari'),
    ('nedhirpur', 'Nedhirpur'),
    ('nehemiah', 'Nehemiah'),
    ('nikla', 'Nikla'),
    ('nimtala', 'Nimtala'),
    ('nischintapur', 'Nischintapur'),
    ('noapara', 'Noapara'),
    ('noapara east', 'Noapara East'),
    ('noapara west', 'Noapara West'),
    ('nonkhawa', 'Nonkhawa'),
    ('nowapara', 'Nowapara'),
    ('nurjahanpur', 'Nurjahanpur'),
    ('nurpur', 'Nurpur'),
    ('oil depot', 'Oil Depot'),
    ('old pitrobaria', 'Old Pitrobaria'),
    ('omorpur', 'Omorpur'),
    ('paikurati', 'Paikurati'),
    ('paitapole', 'Paitapole'),
    ('palashbari', 'Palashbari'),
    ('pangsha', 'Pangsha'),
    ('panishala', 'Panishala'),
    ('papari', 'Papari'),
    ('papkhali', 'Papkhali'),
    ('parbatipur', 'Parbatipur'),
    ('paris road', 'Paris Road'),
    ('parki', 'Parki'),
    ('parshuram', 'Parshuram'),
    ('pathar kul', 'Pathar Kul'),
    ('patiya', 'Patiya'),
    ('patuakhali', 'Patuakhali'),
    ('peda', 'Peda'),
    ('perba', 'Perba'),
    ('petherhat', 'Petherhat'),
    ('phulbari', 'Phulbari'),
    ('phulchhari', 'Phulchhari'),
    ('phultala', 'Phultala'),
    ('pirojpur', 'Pirojpur'),
    ('pirujali', 'Pirujali'),
    ('poba', 'Poba'),
    ('porsha', 'Porsha'),
    ('purba fazilpur', 'Purba Fazilpur'),
    ('purba naodoba', 'Purba Naodoba'),
    ('purba sahapara', 'Purba Sahapara'),
    ('purba sayestaganj', 'Purba Sayestaganj'),
    ('purba terokhada', 'Purba Terokhada'),
    ('purbo baliatali', 'Purbo Baliatali'),
    ('purbo bhurshi', 'Purbo Bhurshi'),
    ('purbo fenchuganj', 'Purbo Fenchuganj'),
    ('purbo monipur', 'Purbo Monipur'),
    ('purbo putimari', 'Purbo Putimari'),
    ('purbo shyampur', 'Purbo Shyampur'),
    ('purbopara', 'Purbopara'),
    ('rabanabad', 'Rabanabad'),
    ('radhanagar', 'Radhanagar'),
    ('rajganj', 'Rajganj'),
    ('rajibpur', 'Rajibpur'),
    ('rajnagar', 'Rajnagar'),
    ('rajo', 'Rajo'),
    ('rajsahi', 'Rajsahi'),
    ('raoan', 'Raoan'),
    ('ratanpur', 'Ratanpur'),
    ('rathbaria', 'Rathbaria'),
    ('rayan', 'Rayan'),
    ('remuna', 'Remuna'),
    ('rompur', 'Rompur'),
    ('roypara', 'Roypara'),
    ('roypur', 'Roypur'),
    ('roypurhat', 'Roypurhat'),
    ('rupganj', 'Rupganj'),
    ('rupsha', 'Rupsha'),
    ('sabdalpur', 'Sabdalpur'),
    ('sahabajpur', 'Sahabajpur'),
    ('sahara', 'Sahara'),
    ('saidpur', 'Saidpur'),
    ('sakhipur', 'Sakhipur'),
    ('salanga', 'Salanga'),
    ('saltha', 'Saltha'),
    ('samta', 'Samta'),
    ('sanarpar', 'Sanarpar'),
    ('santahar', 'Santahar'),
    ('sara', 'Sara'),
    ('sarishabari', 'Sarishabari'),
    ('satkania', 'Satkania'),
    ('shajahanpur', 'Shajahanpur'),
    ('shahrasti', 'Shahrasti'),
    ('shakpura', 'Shakpura'),
    ('sharankhola', 'Sharankhola'),
    ('sheikhala', 'Sheikhala'),
    ('shekhertek', 'Shekhertek'),
    ('sher-e-bangla nagar', 'Sher-E-Bangla Nagar'),
    ('shibchar', 'Shibchar'),
    ('shikarpur', 'Shikarpur'),
    ('shorbaninagar', 'Shorbaninagar'),
    ('shyamnagar', 'Shyamnagar'),
    ('siddhirganj', 'Siddhirganj'),
    ('sindhipara', 'Sindhipara'),
    ('sreepur', 'Sreepur'),
    ('subarna char', 'Subarna Char'),
    ('sundarganj', 'Sundarganj'),
    ('sutrapur', 'Sutrapur'),
    ('sylhet sadar', 'Sylhet Sadar'),
    ('tangail sadar', 'Tangail Sadar'),
    ('taraganj', 'Taraganj'),
    ('tarapur', 'Tarapur'),
    ('tarash', 'Tarash'),
    ('tarashipur', 'Tarashipur'),
    ('tengra', 'Tengra'),
    ('tetulia', 'Tetulia'),
    ('thakur barhi', 'Thakur Barhi'),
    ('thengamara', 'Thengamara'),
    ('thengarhat', 'Thengarhat'),
    ('thimiri', 'Thimiri'),
    ('thumrai', 'Thumrai'),
    ('tongibari', 'Tongibari'),
    ('toraghar', 'Toraghar'),
    ('torikata', 'Torikata'),
    ('torora', 'Torora'),
    ('treongram', 'Treongram'),
    ('tripura', 'Tripura'),
    ('tulshiganj', 'Tulshiganj'),
    ('ultapara', 'Ultapara'),
    ('umarpur', 'Umarpur'),
    ('upara jaurjhari', 'Upara Jaurjhari'),
    ('upara talbagicha', 'Upara Talbagicha'),
    ('upasahar', 'Upasahar'),
    ('uragaon', 'Uragaon'),
    ('vagurmahal', 'Vagurmahal'),
    ('vatpara', 'Vatpara'),
    ('wayale', 'Wayale'),
    ('zirabo', 'Zirabo'),
)